apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==     # base64-encoded 'root'
  MYSQL_DATABASE: ZGV2b3BzY3ViZQ==  # base64-encoded 'devopscube'
  MYSQL_USER: YXJ1bg==              # base64-encoded 'arun'
  MYSQL_PASSWORD: ZGV2b3Bz          # base64-encoded 'devops'
